---
- name: Look for id_rsa_httpd exist
  stat:
    path: /root/.ssh/id_rsa_httpd
  register: file_exist

- name: Generate ssh key pair in local
  command: "ssh-keygen -t rsa -b 2048 -f /root/.ssh/id_rsa_httpd"
  when: file_exist.stat.exists == false